"""The Alembic migrations must produce exactly the schema the ORM models declare,
and upgrades must work on a database that already holds data."""
from __future__ import annotations

from pathlib import Path

from sqlalchemy import create_engine, inspect, text

from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected

ROOT = Path(__file__).resolve().parents[1]


def alembic_config() -> Config:
    cfg = Config(str(ROOT / "alembic.ini"))
    cfg.set_main_option("script_location", str(ROOT / "alembic"))
    return cfg


def test_upgrade_downgrade_roundtrip_and_no_drift(tmp_path, monkeypatch):
    url = f"sqlite:///{tmp_path / 'm.db'}"
    monkeypatch.setenv("DATABASE_URL", url)
    cfg = alembic_config()
    command.upgrade(cfg, "head")
    tables = set(inspect(create_engine(url)).get_table_names())
    assert {"disputes", "evaluations", "reviews", "outcomes", "idempotency_keys"} <= tables

    try:
        command.check(cfg)
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - failure path
        raise AssertionError(f"models and migrations have drifted: {exc}") from exc

    command.downgrade(cfg, "base")
    assert set(inspect(create_engine(url)).get_table_names()) <= {"alembic_version"}


def test_audit_log_migration_backfills_existing_rows(tmp_path, monkeypatch):
    url = f"sqlite:///{tmp_path / 'm.db'}"
    monkeypatch.setenv("DATABASE_URL", url)
    cfg = alembic_config()
    command.upgrade(cfg, "0001")
    engine = create_engine(url)
    with engine.begin() as c:
        c.execute(text("INSERT INTO disputes VALUES ('c1','mch_01','13.1','not_received',1000,'2026-01-01')"))
        c.execute(text(
            "INSERT INTO evaluations (case_id, created_at, input_hash, action, confidence, p_win, p_win_std, "
            "ev_contest_inr, contest_cost_inr, review_value_inr, review_cost_inr, facts, fact_agreement, "
            "unread_facts, conflicts, reasons, counterfactual, contributions, extraction_source, llm_calls, "
            "llm_tokens, model_version, latency_ms, input_snapshot, merchant_snapshot) VALUES "
            "('c1','2026-01-01','h','CONTEST','HIGH',0.5,0,1,1,0,1,'{}','{}','[]','[]','[]','{}','{}','rules',"
            "0,0,'wm',0,'{}','{}')"))
    command.upgrade(cfg, "head")
    with engine.connect() as c:
        assert c.execute(text("SELECT audit_log FROM evaluations")).scalar_one() == "[]"
